# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapChat
source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'
pod 'GooglePlaces'

  target 'MapChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
